default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: ["--profile", "black"]

  - repo: https://github.com/myint/autoflake
    rev: v2.2.1
    hooks:
    - id: autoflake
      args: [
        --in-place,
        --remove-unused-variables,
        --remove-all-unused-imports,
      ]

  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
    - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.6.1
    hooks:
    - id: mypy
      additional_dependencies: [
        types-requests
      ]
      args: [
        --strict,
        --ignore-missing-imports,
        --allow-untyped-decorators
      ]

  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
      args: ['--ignore=D213,D203,D204,D416']
      additional_dependencies: ["tomli"]

  - repo: local
    hooks:
    - id: pycodestyle
      name: pycodestyle
      entry: pycodestyle
      language: system
      args: [
        '--ignore=E722,E126',
        '--max-line-length=80',
        '--exclude=*init*'
      ]
      files: \.py$

  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.4
    hooks:
    - id: bandit

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: trailing-whitespace
      exclude: ^.gitlab/
    - id: end-of-file-fixer
      exclude: ^.gitlab/
    - id: check-yaml
      args: [--allow-multiple-documents]
    - id: check-added-large-files
    - id: detect-private-key
